# Project: P3Lab9
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o ArchivoBin.o Soldado.o SAsalto.o SSoporte.o
LINKOBJ  = main.o ArchivoBin.o Soldado.o SAsalto.o SSoporte.o
LIBS     = -L"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/lib" -L"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/include" -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/include" -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = P3Lab9.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

ArchivoBin.o: ArchivoBin.cpp
	$(CPP) -c ArchivoBin.cpp -o ArchivoBin.o $(CXXFLAGS)

Soldado.o: Soldado.cpp
	$(CPP) -c Soldado.cpp -o Soldado.o $(CXXFLAGS)

SAsalto.o: SAsalto.cpp
	$(CPP) -c SAsalto.cpp -o SAsalto.o $(CXXFLAGS)

SSoporte.o: SSoporte.cpp
	$(CPP) -c SSoporte.cpp -o SSoporte.o $(CXXFLAGS)
